name: "classic_googlenet_cifar10"
version: "1.0.0"
description: "Classical GoogLeNet model for CIFAR10 dataset"

data:
  name: "CIFAR10"
  dataset_type: "CIFAR10"
  input_shape: [3, 32, 32]
  num_classes: 10
  dataset_path: "datasets"
  train_split: 0.8
  batch_size: 32
  num_workers: 2
  pin_memory: false
  train_transforms:
    - name: "RandomCrop"
      args:
        size: [32, 32]
        padding: 4
    - name: "RandomHorizontalFlip"
    - name: "ToTensor"
    - name: "Normalize"
      args:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  val_transforms:
    - name: "ToTensor"
    - name: "Normalize"
      args:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  test_transforms:
    - name: "ToTensor"
    - name: "Normalize"
      args:
        mean: [0.4914, 0.4822, 0.4465]
        std: [0.2023, 0.1994, 0.2010]
  dataset_kwargs:
    download: true

model:
  name: "SimpleGoogLeNet"
  model_type: "classic"
  model_kwargs:
    aux_logits: true
    dropout: 0.3
    dropout_aux: 0.4
  quantum_config: null
  custom_model_path: null

training:
  learning_rate: 1e-3
  weight_decay: 5e-4
  num_epochs: 10
  checkpoint_interval: 1
  scheduler_type: "StepLR"
  scheduler_kwargs:
    step_size: 5
    gamma: 0.5

device: "mps"
seed: 42
output_dir: "./outputs"
