name: "classic_fashionmnist"
version: "1.0.0"
description: "Classic CNN model for FashionMNIST dataset"

data:
  name: "FashionMNIST"
  dataset_type: "FASHIONMNIST"
  input_shape: [1, 28, 28]
  num_classes: 10
  dataset_path: "datasets"
  train_split: 0.8
  batch_size: 64
  num_workers: 4
  pin_memory: true
  train_transforms:
    - name: "ToTensor"
    - name: "Normalize"
      args:
        mean: [0.2860]
        std: [0.3530]
  val_transforms:
    - name: "ToTensor"
    - name: "Normalize"
      args:
        mean: [0.2860]
        std: [0.3530]
  test_transforms:
    - name: "ToTensor"
    - name: "Normalize"
      args:
        mean: [0.2860]
        std: [0.3530]
  dataset_kwargs:
    download: true

model:
  name: "ClassicNet"
  model_type: "classic"
  model_kwargs: {}
  quantum_config: null
  custom_model_path: null

training:
  learning_rate: 1e-3
  weight_decay: 1e-4
  num_epochs: 10
  checkpoint_interval: 1
  scheduler_type: "StepLR"
  scheduler_kwargs:
    step_size: 5
    gamma: 0.5

device: "cpu"
seed: 42
output_dir: "./outputs"
